2018-10-24 11:19:36,884 - s1 - ERROR:  Traceback (most recent call last):
  File "C:\Users\hexun\envs\auto_client\src\plugins\disk.py", line 23, in linux
    output = open(os.path.join(self.base_dir,'file/disk.out'), 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hexun\\envs\\auto_client\\file/disk.out'

